### ISSUE TITLE
Bump prost to 0.13

### ISSUE THREAD

**Issue by Buckram123** [osmosis-labs/osmosis-rust#117]
Currently in this repo, 3 different versions of prost used. 
```toml
prost = {version = "0.12.3", default-features = false, features = ["prost-derive"]}
prost = "0.10"
prost-types = "0.11.9"
```
Would be great to see it's unified and bumped to the latest
